#!/bin/bash
###depends
#curl
#popd/pushd
#sed
#tar
#bdstar
#makefs.vfat/makefs.ext4

######################i am currently coding from work... windows..... scpipt may be extra unstable untested code, all the functional parts are at the bottom below the functions, you can just edit the variables and select y at the menu
echo creating variables
export SDDEV="/dev/sda"
export SDPARTBOOT=${SDDEV}1
export SDPARTROOT=${SDDEV}2 #depending on weather one is using usb or nvme, user may need to change this to p1 and p2 respectively.

export SDMOUNT="/mnt/SD"

export DLDIR="~$SUDO_USER/Documents/a4pFiles" #trying this later
#export DLDIR="$HOME/Documents/a4pFiles" #when ran as sudo chooses root directory, undesirable.  use ~$SUDO_USER here and elsewhere, and notify user when selecting their own paths.#or use sudo -e?   perhaps this: USER_HOME=$(eval echo "~$SUDO_USER")
#export DLDIR="/tmp/a4pTMP"

export DISTURL="http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-aarch64-latest.tar.gz"
export RPIKURL="https://fl.us.mirror.archlinuxarm.org/aarch64/core/linux-rpi-6.18.15-1-aarch64.pkg.tar.xz"
#find raspi kernel link here if updated https://fl.us.mirror.archlinuxarm.org/aarch64/core/

export LOCALFILES="n"
#export LOCALFILES="n"


a4pDev() {
    while true; do
        lsblk
        
        read -p "Enter the name of the storage device. NOTE, drives may not appear as you think they may due to things like SD to usb adapters, nvme to usv adapters: " input

		if [[ -b "/dev/$input" ]]; then
            SDDEV="/dev/$input"
        else
            echo "Invalid selection. Enter a valid storage device name."
            continue
        fi
        
        # Confirm the selected device
        echo "You have selected: $SDDEV"
        read -p "This device will be overwritten, confirm (y/n)? " confirm
        if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
            echo "Storage device confirmed: $SDDEV"
            break
        else
            echo "Try again."
        fi
    done
}

###bROKEN
a4pChoose() {
local oldDLDIR="$DLDIR"
local oldDISTURL="$DISTURL"
    while true; do
        read -p "Do you want to (d)ownload files or (s)elect existing files? (Enter d or s): " choice

        if [[ "$choice" == "d" || "$choice" == "D" ]]; then
            # Prompt for the download URL
		read -p "Enter the URL to download from (default is $oldDISTURL)" url  #CHANGES MADE TO KEEP OLD DEFAULT UNTIL CONFIRM TEST THIS
		DISTURL="${url:-$oldDISTURL}"  # set to DISTURL if no input is provided #CHANGED url to DISTURL
            echo "You have selected download URL: $DISTURL"

            # Confirm the download URL
            read -p "Confirm this URL (y/n)? " confirm_url
            if [[ "$confirm_url" == "y" || "$confirm_url" == "Y" ]]; then
                echo "Download URL confirmed: $DISTURL"
                LOCALFILES=n

                # Prompt for the directory to save installation files    ###ITHINK THIS FAILS DUE TO DIR NOT CREATED YET
                read -p "Choose a path to save installation files, any dir in /tmp will be deleted upon exit, if a dir doesn't exist, it will be created (default is $DLDIR): " path
                DLDIR="${path:-$oldDLDIR}"  #changed recently
                echo "You have selected: $DLDIR"
                
                # Confirm the installation directory
                read -p "Confirm this path (y/n)? " confirm_path
                if [[ "$confirm_path" == "y" || "$confirm_path" == "Y" ]]; then
                    echo "Installation path confirmed: $DLDIR"
					LOCALFILES="n"
                    break
                else
                    echo "Let's try again."
                fi
            else
                echo "Let's try again."
            fi
            
        elif [[ "$choice" == "s" || "$choice" == "S" ]]; then
            # Prompt for the existing files path
            read -p "Enter the directory path for existing files with the OS img or iso in the directory and the RPI kernel in <dir>/linux-rpi/: " path
            DLDIR="$path"
            
            # Confirm the existing files path
            echo "You have selected: $DLDIR"
            read -p "Confirm this path (y/n)? " confirm_path
            if [[ "$confirm_path" == "y" || "$confirm_path" == "Y" ]]; then
                echo "Existing files path confirmed: $DLDIR"
                LOCALFILES="y"
                break
            else
                echo "Let's try again."
            fi
            
        else
            echo "Invalid option. Enter 'd' to download or 's' to select existing files."
        fi
    done
}


#do not use fstab fixer yet

fstabFixer() {  #TEST SO SEE IF WE CAN RUN THIS FOR SD CARDS WITH NO ILL EFECTS, in which case we will make it auto run every installation

while true; do

        read -p "If the device is not an SD card, /etc/fstab needs to be modified, press y to continue to fix fstab." input

        if [[ "$input" == "y" ]]; then
			# Store all partitions into an array (skipping the first entry which is the disk itself)
			mapfile -t PARTS < <(lsblk -nlo NAME "$SDDEV" | tail -n +2)
			SDPARTBOOT="/dev/${PARTS[0]}"
			SDPARTROOT="/dev/${PARTS[1]}"

		else
			break
		fi
done
}



#DUM DUM METHOD
#DEVICE="/dev/sda"
# 1. Get the first partition (index 1)
#SDPARTBOOT="/dev/$(lsblk -nlo NAME "$DEVICE" | sed -n '2p')"
# 2. Get the second partition (index 2)
#SDPARTROOT="/dev/$(lsblk -nlo NAME "$DEVICE" | sed -n '3p')"
# Display results
#echo "Boot Partition: $SDPARTBOOT"
#echo "Root Partition: $SDPARTROOT"



# Function to allow user to redo previous steps or continue
a4pMenu() {
    while true; do
        echo "Y for default options or select any steps below to reconfigure."
        echo '1) Select storage device'
        echo '2) Select download URL or existing directory path'
        echo '4) Continue (or type y)'

        read -p 'Select an option (1-4 or y): ' option
        
        # Check if user typed 'y' for continue
        if [[ "$option" == "y" ]]; then
            echo "Proceeding with the selected options..."
            return
        fi

        case $option in
            1)
                a4pDev
                ;;
            2)
                a4pChoose
                ;;
            4)
                echo "Proceeding with the selected options..."
                return
                ;;
            *)
                echo "Invalid option. Please select a valid number or y to continue."
                ;;
        esac
    done
}



# Start the process with the a4pmenu function
a4pMenu



echo "You have selected $SDDEV as your storage device to overwrite."
#echo "You have selected $DLDIR as your installation files directory."
if [[ $LOCALFILES == "n" ]]; then
	echo "You have selected $DISTURL to download to $DLDIR."
else
	echo "You have selected to install from $OSFILES."
fi
echo "$SDDEV will be mounted at $SDMOUNT."

read -p "Does everything look correct? y to execute program with given parameters, any other key for menu." choice
if [[ "$choice" == "y" ]]; then
	:
else
	ap4menu
fi

#exit

############################functional part pasted in


if [[ "$LOCALFILES" == "n" ]]; then
	echo  make directory for arch image DL
	mkdir -p "$DLDIR"
	cd "$DLDIR" || { echo "cd failed, returning to menu."; a4pMenu; }
	curl -JLO "$DISTURL"
else
	cd "$DLDIR" || { echo "cd failed, returning to menu."; a4pMenu; }
fi


##make partition helper for dumeez
echo "format device"
sudo sfdisk --quiet --wipe always "$SDDEV" << EOF
,512M,0c,
,,,
EOF

	echo "create filesystem"
sudo mkfs.vfat -F 32 "$SDPARTBOOT"
sudo mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0 -F "$SDPARTROOT"

	echo "write image to disk, this will take a while."
mkdir -p "$SDMOUNT"
mount "$SDPARTROOT" "$SDMOUNT"
mkdir -p ${SDMOUNT}/boot
mount "$SDPARTBOOT" ${SDMOUNT}/boot

bsdtar -xvpf ${DLDIR}/${DISTURL##*/} -C "$SDMOUNT"
#bsdtar -xvpf ${DLDIR}/ArchLinuxARM-rpi-aarch64-latest.tar.gz -C $SDMOUNT



  echo remove arch bootloader
rm -rf ${SDMOUNT:?}/boot/* || { echo "failed to remove arch bootloader, returning to menu"; a4pMenu; }



  echo "install raspi kernel"
if [[ "$LOCALFILES" == n ]]; then    #TEST THIS
	mkdir -p ${DLDIR}/linux-rpi
	pushd ${DLDIR}/linux-rpi || { echo "failed to change to rpi kernel folder, returning to menu."; a4pMenu; }
	#####################################problems
	curl -JLO "$RPIKURL"
else
	pushd ${DLDIR}/linux-rpi || { echo "failed to change to rpi kernel folder, returning to menu."; a4pMenu; }
fi

#ARE WE CD TO SAME DIR TWICE??
cd ${DLDIR}/linux-rpi || { echo "failed to change to rpi kernel folder, returning to menu."; a4pMenu; }

tar xf ${DLDIR}/linux-rpi/${RPIKURL##*/}
#tar xf ${DLDIR}/linux-rpi/linux-rpi-6.12.58-1-aarch64.pkg.tar.xz

cp -rf boot/* ${SDMOUNT}/boot/
popd || { echo "failed to change dir, returning to menu."; a4pMenu; }


# Source - https://stackoverflow.com/a/9606535
# Posted by jcollado, modified by community. See post Timeline for change history
# Retrieved 2026-03-05, License - CC BY-SA 3.0


echo "Set boot and root var names and find PARTUUID to fix /etc/fstab and /boot/cmdline.txt ...For SSD and usb users"

	mapfile -t PARTS < <(lsblk -nlo NAME "$SDDEV" | tail -n +2)  #first intelligently set var names from array
	SDPARTBOOT="/dev/${PARTS[0]}"
	SDPARTROOT="/dev/${PARTS[1]}"

	sudo blkid
	export BOOTPUUID="PARTUUID="$(sudo blkid -s PARTUUID -o value "$SDPARTBOOT") #this works   shellcheck says(warning): Declare and assign separately to avoid masking return values.
	export ROOTPUUID="PARTUUID="$(sudo blkid -s PARTUUID -o value "$SDPARTROOT")
	#echo $BOOTPUUID
	#echo $ROOTPUUID

echo "Backing up and updating /etc/fstab"
	sed -i.bac "s|/dev/mmcblk0p1|${BOOTPUUID}|g" ${SDMOUNT}/etc/fstab
	#echo "${ROOTPUUID}  /   vfat    defaults        0       0" >> ${SDMOUNT}/etc/fstab

echo "backup and update /boot/cmdline.txt"
	sed -i.bac "s|root=/dev/mmcblk0p2|root=${ROOTPUUID}|g" ${SDMOUNT}/boot/cmdline.txt #this works well


echo "Syncing, takes a while patience"
sync && umount -R $SDMOUNT
echo "COMPLETED. Eject and boot pi"

if [[ "$DLDIR" == /tmp* ]]; then
	rm -r "$DLDIR" || { echo "failed to delete OS install files at $DLDIR"; exit; }
	echo "debug for del tmp"
fi

echo "Clean up after ourself, exiting."
rm -r $SDMOUNT || { echo "faailed to delete mount folder at $SDMOUNT"; exit; }
exit


####################################
#
#choose device
#
#choose existing files or download path
#
#download to tmp or save files
#
#partitioner prompt goes here
#
#confirm okay
#
#format
#partition
#writeFS
#
#
#
#
#fstab fixer for non SD users automatic
#
#
#####massive thanks to those who i stole from
#https://kiljan.org/2023/11/24/arch-linux-arm-on-a-raspberry-pi-5-model-b/
#
#https://fleetstack.io/blog/raspberry-pi-etc-fstab-txt-file
#
#https://github.com/literatesnow/pi-5-archlinux-arm-encrypted-root
#
#
#
