#!/bin/bash
###depends
#curl
#popd/pushd
#sed
#tar
#bdstar
#makefs.vfat/makefs.ext4

######################i am currently coding from work... windows..... scpipt may be extra unstable untested code, all the functional parts are at the bottom below the functions, you can just edit the variables and select y at the menu
echo creating variables
export SDDEV=/dev/sdb
export SDPARTBOOT=${SDDEV}1 #automatically changes later
export SDPARTROOT=${SDDEV}2 #depending on weather one is using usb or nvme, user may need to change this to p1 and p2 respectively.

export SDMOUNT=/mnt/SD

export DLDIR="/home/$SUDO_USER/a4pFiles" #trying this later
#export DLDIR=/tmp/a4pTMP

export DISTURL="http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-aarch64-latest.tar.gz"
export RPIKURL="https://fl.us.mirror.archlinuxarm.org/aarch64/core/linux-rpi-6.18.16-2-aarch64.pkg.tar.xz"
#find raspi kernel link here if updated https://fl.us.mirror.archlinuxarm.org/aarch64/core/

export LOCALFILES=n

export AFTERBOOT=y
export FSTABFIXER=y

a4pDev() {
    while true; do
	clear
        lsblk
        echo
        read -p "Enter the name of the storage device. NOTE, drives may not appear as you think they may due to things like SD to usb adapters, nvme to usv adapters: " input

	if [[ -b "/dev/$input" ]]; then
            SDDEV="/dev/$input"
        else
	    clear
            echo "Invalid selection. Enter a valid storage device name."
	    a4pMenu
            #continue
        fi

        # Confirm the selected device
        echo "You have selected: $SDDEV"
        read -p "This device will be overwritten, confirm (y/n)? " confirm
        if [[ $confirm == "y" || $confirm == "Y" ]]; then
        	echo "Storage device confirmed: $SDDEV"
		clear
       		break
        else
            echo "Try again."
        fi
    done
}


a4pChoose() {
clear
local oldDLDIR=$DLDIR
local oldDISTURL=$DISTURL
    while true; do
        read -p "Do you want to (d)ownload files or (s)elect existing files? (Enter d or s): " choice

        if [[ $choice == "d" || $choice == "D" ]]; then
            # Prompt for the download URL
		clear
		read -p "Enter the URL to download from (default is $oldDISTURL)" url  #CHANGES MADE TO KEEP OLD DEFAULT UNTIL CONFIRM TEST THIS
			DISTURL="${url:-$oldDISTURL}"  # set to DISTURL if no input is provided #CHANGED url to DISTURL
	    		echo
            		echo "You have selected download URL: $DISTURL"

            # Confirm the download URL
		echo
        	read -p "Confirm this URL (y/n)? " confirm_url
			clear
           		if [[ $confirm_url == "y" || "$confirm_url" == "Y" ]]; then
                	echo "Download URL confirmed: $DISTURL"
               		LOCALFILES=n

                # Prompt for the directory to save installation files    ###ITHINK THIS FAILS DUE TO DIR NOT CREATED YET
		echo
                read -p "Choose a path to save installation files, any dir in /tmp will be deleted upon exit, if a dir doesn't exist, it will be created (default is $DLDIR): " path   ###ISTHISGUNNABLOWMUD
                DLDIR="${path:-$oldDLDIR}"  #changed recently
		echo
                echo "You have selected: $DLDIR"

                # Confirm the installation directory
		echo
                read -p "Confirm this path (y/n)? " confirm_path
                if [[ $confirm_path == "y" || $confirm_path == "Y" ]]; then
			clear
			echo "Installation path confirmed: $DLDIR"
			LOCALFILES=n
                	break
                else
			clear
                    	echo "Let's try again."
                fi
            else
                echo "Let's try again."
            fi

        elif [[ $choice == "s" || $choice == "S" ]]; then
            # Prompt for the existing files path
		clear
        	read -p "Enter the directory path for existing files with the OS img or iso in the directory and the RPI kernel in <dir>/linux-rpi/: " path  #DOES PI EVEN USE ISO OR IMG QUESTION
        	DLDIR=$path

            # Confirm the existing files path
		echo
        	echo "You have selected: $DLDIR"
		echo
            	read -p "Confirm this path (y/n)? " confirm_path
           	 if [[ $confirm_path == "y" || "$confirm_path" == "Y" ]]; then
			clear
                	echo "Existing files path confirmed: $DLDIR"
                	LOCALFILES=y
                	break
            	else
			clear
                	echo "Let's try again."
            	fi

        else
            echo "Invalid option. Enter 'd' to download or 's' to select existing files."
        fi
    done
}


a4pAfter() {
	clear

}


a4pConfirm() {
clear
	echo "You have selected $SDDEV as your storage device to overwrite and install to."
	echo "$SDDEV will be mounted at $SDMOUNT."

	if [[ $LOCALFILES == "n" || $LOCALFILES == "N" ]]; then
		echo "You have to download from $DISTURL to $DLDIR."
	else
		echo "You have selected to install existing installation files from $DLDIR."
	fi

	while true; do  #test this crapCRAPCODE
		echo
		read -p "Does everything look correct? y to execute program with given parameters, any other key for menu." choice
		if [[ $choice == "y" || $choice == "Y" ]]; then
			clear
			return
		else
			clear
			a4pMenu
		fi
	done
}


# Function to allow user to redo previous steps or continue
a4pMenu() {
    while true; do
        echo "Y for default options or select any steps below to reconfigure."
        echo '1) Select storage device'
        echo '2) Select download URL or existing directory path'
        echo '4) Continue (or type y)'

        read -p "Select an option (1-4 or y): " option

        # Check if user typed 'y' for continue
        if [[ $option == "y" || $option == "Y"  ]]; then
            echo "Proceeding with the selected options..."
            return
        fi

        case $option in
            1)
                a4pDev
                ;;
            2)
                a4pChoose
                ;;
	    3)
		a4pAfter
		;;
            4)
                return
                ;;
            *)
                echo "Invalid option. Please select a valid number or y to continue."
                ;;
        esac
    done
}


############################functional part pasted in
#####################################################

a4pDLAlarm() {
if [[ $LOCALFILES == "n" || $LOCALFILES == "N" ]]; then
	echo  "make directory for arch image at $DLDIR"
	#####cd /home/$SUDO_USER
	mkdir -p "$DLDIR"
	cd "$DLDIR" # || { echo "cd failed, returning to menu."; a4pMenu; }
	curl -JLO "$DISTURL"
else
	####cd "$DLDIR" # || { echo "cd failed, returning to menu."; a4pMenu; }
	echo "do we even need this"
fi
}


##make partition helper for dumeez
a4pPart() {
echo "format and partition $SDDEV"
sudo sfdisk --quiet --wipe always "$SDDEV" << EOF
,512M,0c,
,,,
EOF
}


a4pPartVar() {
#WE NEED TO FIGURE OUT SDPARTBOOT AND ROOT HERE
# Store all partitions into an array (skipping the first entry which is the disk itself)
mapfile -t PARTS < <(lsblk -nlo NAME "$SDDEV" | tail -n +2)
SDPARTBOOT="/dev/${PARTS[0]}"
SDPARTROOT="/dev/${PARTS[1]}"
echo "Boot Partition: $SDPARTBOOT"
echo "Root Partition: $SDPARTROOT"
}


a4pFS() {
	echo "create filesystem"
sudo mkfs.vfat -F 32 "$SDPARTBOOT"
sudo mkfs.ext4 -E lazy_itable_init=0,lazy_journal_init=0 -F "$SDPARTROOT"
}


a4pMNT() {
echo "creating mount at $SDMOUNT"
mkdir -p "$SDMOUNT"
mount "$SDPARTROOT" "$SDMOUNT"
mkdir -p "${SDMOUNT}"/boot
mount "$SDPARTBOOT" ${SDMOUNT}/boot
}


a4pWAlarm() {
echo "write image to disk, this will take a while."
bsdtar -xvpf "${DLDIR}"/"${DISTURL##*/}" -C "$SDMOUNT"
#bsdtar -xvpf ${DLDIR}/ArchLinuxARM-rpi-aarch64-latest.tar.gz -C $SDMOUNT

echo "remove arch bootloader"
rm -rf ${SDMOUNT:?}/boot/* || { echo "failed to remove arch bootloader, returning to menu"; a4pMenu; }

}


####THIS CODE IS SUSPECT
a4pDLKernel() {
if [[ $LOCALFILES == "n" || $LOCALFILES == "N" ]]; then    #TEST THIS
	echo "making linux-rpi dir for rpi kernel"
	mkdir -p "${DLDIR}"/linux-rpi
	pushd "${DLDIR}"/linux-rpi || { echo "failed to change to rpi kernel folder, returning to menu."; a4pMenu; }

	echo "downloading alarm"
	curl -JLO "$RPIKURL"

else
	pushd "${DLDIR}"/linux-rpi || { echo "failed to change to rpi kernel folder, returning to menu."; a4pMenu; }
	echo "not downloading alarm"
fi
}


a4pKernel() {
pushd "${DLDIR}"/linux-rpi || { echo "failed to change to rpi kernel folder, returning to menu."; a4pMenu; }
echo "install raspi kernel at $PWD"
#ARE WE CD TO SAME DIR TWICE??
tar -xf "${DLDIR}"/linux-rpi/"${RPIKURL##*/}"
#tar -xf "${DLDIR}"/linux-rpi/linux-rpi*
cp -rf boot/* ${SDMOUNT}/boot/
popd || { echo "failed to change dir, returning to menu."; a4pMenu; }
}


a4pFSTAB() {
if [[ $FSTABFIXER == "y" || $FSTABFIXER == "Y" ]]; then
	echo "Backing up and updating /etc/fstab"

	sed -i.bac "s|/dev/mmcblk0p1|${BOOTPUUID}|g" ${SDMOUNT}/etc/fstab
#	echo "${BOOTPUUID}  /boot   vfat    defaults        0       0" >> ${SDMOUNT}/etc/fstab
	echo "${ROOTPUUID}  /   ext4    defaults        0       0" >> ${SDMOUNT}/etc/fstab

	echo "backup and update /boot/cmdline.txt"

	sed -i.bac "s|root=/dev/mmcblk0p2|root=${ROOTPUUID}|g" ${SDMOUNT}/boot/cmdline.txt #this works well
#	echo "root=${ROOTPUUID} rw rootwait console=serial0,115200 console=tty1 fsck.repair=yes splash quiet loglevel=3" > ${SDMOUNT}/boot/cmdline.txt


fi
}


a4pAB() {
if [[ $AFTERBOOT == "y" || $AFTERBOOt == "Y" ]]; then

cat << EOF > $SDMOUNT/root/afterBoot.txt
pacman-key --init
pacman-key --populate archlinuxarm

pacman -R linux-aarch64 uboot-raspberrypi
pacman -Syu --overwrite "/boot/*" linux-rpi
EOF
echo "afterboot file successfully installed at $SDMOUNT/root/afterBoot.txt"

fi
}

# Start the process with the a4pmenu function
a4pMenu

#a4pDev
#a4pChoose

a4pConfirm

a4pDLAlarm

a4pPart

a4pPartVar

a4pFS

a4pMNT

a4pWAlarm

a4pDLKernel

a4pKernel

#a4pFSTAB

a4pAB

echo "Syncing, takes a while patience"
sync && umount -R $SDMOUNT
echo "COMPLETED. Eject and boot pi"

if [[ "$DLDIR" == /tmp* ]]; then
	rm -r "$DLDIR" || { echo "failed to delete OS install files at $DLDIR"; exit; }
	echo "debug for del tmp"
fi

echo "Clean up after ourself, exiting."
rm -r "$SDMOUNT" || { echo "failed to delete mount folder at $SDMOUNT"; exit; }
exit


####################################
#
#files in tmp are deleted upon exit
#
#
#
#fstab fixer for non SD users automatic hopefully
#
#ask to inject afterboot file into root, useful if one does not have more than one computer
#
######massive thanks to those who i stole from
#
#https://kiljan.org/2023/11/24/arch-linux-arm-on-a-raspberry-pi-5-model-b/
#
#https://fleetstack.io/blog/raspberry-pi-etc-fstab-txt-file
#
#https://github.com/literatesnow/pi-5-archlinux-arm-encrypted-root
##
# Source - https://stackoverflow.com/a/9606535
# Posted by jcollado, modified by community. See post Timeline for change history
# Retrieved 2026-03-05, License - CC BY-SA 3.0
